---
title: "Code_book"
author: "Luca Santabarbara"
date: "2/4/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Code Book -- Assignment 3

**Subject**\
Identifies each subject who took part at the experiment. \
Goes from 1 to 30\
  
**Activity**\
1. Walking\
2. Walking Upstairs\
3. Walking Downstairs\
4. Sitting\
5. Standing\
6. Lying\
  
**Features**\
Features are filtered by mean and standard deviation of each element.\
1. tBodyAcc = Time Body Accelerometer.\
2. tGravityAcc = Time Gravity Accelerometer.\
3. tBodyAccJerk = Time Body Accelerometer Jerk.\
4. tBodyGyro = Time Body Gyroscope Jerk.\
5. tBodyGyroJerk = Time Body Gyroscope Jerk.\
6. tBodyAccMag = Time Body Accelerometer Magnitude.\
7. tGravityAccMag = Time Gravity Accelerometer Magnitude.\
8. tBodyAccJerkMag = Time Body Accelerometer Jerk Magnitude.\
9. tBodyGyroMag = Time Body Gyroscope Magnitude\
10. tBodyGyroJerkMag = Time Body Gyroscope Jerk Magnitude.\
11. fBodyAcc = Frequency Body Accelerometer.\
12. fBodyAccJerk = Frequency Body Jerk.\
13. fBodyGyro = Frequency Body Gyroscope.\
14. fBodyAccMag = Frequency Body Accelerometer Magnitude.\
15. fBodyBodyAccJerkMag = Frequency Body Accelerometer Jerk Magnitude.\
16. fBodyBodyGyroMag = Frequency Body Gyroscope Magnitude.\
17. fBodyBodyGyroJerkMag = Frequency Body Gyroscope Jerk Magnitude.\
