---
title: "Read_ME"
author: "Luca Santabarbara"
date: "3/4/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Assignment 3 Read Me

The aim of the assignment is to gather data from the following 
[link]( https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip ).

To do so, an R file is needed, Run_analysis, which does the following:\
1. Merges the training and the test sets to create one data set.\
2. Extracts only the measurements on the mean and standard deviation 
for each measurement.\
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names.\
5. From the data set in step 4, creates a second, independent tidy data set 
with the average of each variable for each activity and each subject.\
\
The script takes in input:\
1. Features: a list of all features of the experiment.\
2. Activities labels: a description of all 6 activities.\
3. Observations: test and train data for each feature.\
4. Subjects: list of 30 subjects.\
\
After having merged all together, it reshapes the data, returning a tiny dataset, 
called mydata:\

- Column one collects each subject.\
- Column two collects the activity for each subject.\
- Column three collects the description of that activity.\
- Column 4 to 69 collect mean and std for each feature, for a total of 10299
observations.\

